definitions:
  server.Node:
    properties:
      height:
        type: integer
      network:
        type: string
      note:
        type: string
      point:
        type: integer
      time_since_now:
        type: string
      timestamp:
        type: integer
      url:
        type: string
      weight:
        type: integer
    type: object
  server.RespJsonObj:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: joy060102@gmail.com
    name: joy
    url: https://github.com/jooyyy
  description: service doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: vsys nodes health service doc
  version: "1.0"
paths:
  /api/node/:network:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return an active node url
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.RespJsonObj'
      summary: Get node by network type
      tags:
      - Nodes
  /api/node/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: return an active node url
          schema:
            items:
              $ref: '#/definitions/server.Node'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.RespJsonObj'
      summary: Get all nodes information
      tags:
      - Nodes
swagger: "2.0"
